### ISSUE TITLE
Conflict on /web deployment

### ISSUE THREAD

**Issue by Darkdias** [Microsoft/AzureNetworkWatcherNSGFlowLogsConnector#10]
We have an error "conflict" during app deployment on the resource "appName/web"

The resource type is "Microsoft.Web/sites/sourcecontrols"

Any idea ?

Thank you,

![screencaperror](https://user-images.githubusercontent.com/9880416/54427604-480cd380-471b-11e9-9566-a67c9c7f9297.jpg)

**Comment by sebastus** [comment]
Can you try it again with the current installation template? I made changes recently and we should be using the same thing before trying to debug.

**Comment by sujith-es** [comment]
@sebastus  @Darkdias I was also facing the same issue with the latest `master` code.

Forked the repo 
```AzureNetworkWatcherNSGFlowLogsConnector``` and ```AzureFunctionDeployment``` and verified.

Below are the commits

https://github.com/sujith-es/AzureNetworkWatcherNSGFlowLogsConnector/commit/c3b8d4dbfcaee8b7efd64d7da2abe86f16632ef3

https://github.com/sebastus/AzureFunctionDeployment/pull/7/commits/9049b311a070967d6a48ab10bd87b44c3a3246bf
