### ISSUE TITLE
Missing Logstash

### ISSUE THREAD

**Issue by cybermohr** [Microsoft/AzureNetworkWatcherNSGFlowLogsConnector#15]
In the template for custom deployment, I have selected "Logstash" for the Output binding, but don't seen anything for the connection settings. Only Arksight, Splunk and Event Hub.

**Comment by sebastus** [comment]
I removed the Logstash output binding a while back because of lack of demand + the need to test the configuration. If you want to add it back and test the operation, look at line 94 of util.cs. To see the required settings, look at line 15 of obLogstash.cs.
