### ISSUE TITLE
Version 2 NSGFlowLogTuple Schema broke build during Functions Deploy

### ISSUE THREAD

**Issue by dxlusby** [Microsoft/AzureNetworkWatcherNSGFlowLogsConnector#3]
It would appear that the addition of the version parameter in the August changes causes the project build to fail.

Using shared compilation with compiler from directory: D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\15.0\Bin\Roslyn
Stage1BlobTrigger.cs(50,20): warning CS0168: The variable 'msg' is declared but never used [D:\home\site\repository\NwNsgProject\NwNsgProject.csproj]
Stage3QueueTrigger.cs(484,45): error CS7036: There is no argument given that corresponds to the required formal parameter 'version' of 'NSGFlowLogTuple.NSGFlowLogTuple(string, float)' [D:\home\site\repository\NwNsgProject\NwNsgProject.csproj]
Done Building Project "D:\home\site\repository\NwNsgProject\NwNsgProject.csproj" (default targets) -- FAILED.

**Comment by sebastus** [comment]
Hi @dxlusby. If you install from the 'refactorOutputs' branch, this problem is fixed. I'll merge the branch into master once there is more testing. Care to contribute?

**Comment by sebastus** [comment]
Version 2 is merged.
