### ISSUE TITLE
NSG Flow Logs to Event Hub

### ISSUE THREAD

**Issue by markhoiland** [Microsoft/AzureNetworkWatcherNSGFlowLogsConnector#8]
Hello. It appears that the option to send the flow logs directly to an Azure Event Hub were added to this code, but when attempting to use it the events don't appear to be getting picked up by the Event Hub. Is that functionality possible now using this function app deployment?

**Comment by sebastus** [comment]
I'm just merging another PR related to that. Please give it another try and let me know what you find.

**Comment by akgopal** [comment]
Hi, the nsgflowevents still don't appear in the event hub.  nsgrulecounters and nsgevents are published.  Is this issue still open.

**Comment by sebastus** [comment]
The feature is tested and merged with master branch. Check your settings and ensure that the output binding is "eventhub" and all other settings are correct.
